// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MensagemBDT.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Infra.Shared.Proto
{

    /// <summary>Holder for reflection information generated from Mensagem.proto</summary>
    public static partial class MensagemReflection
    {

        #region Descriptor
        /// <summary>File descriptor for Mensagem.proto</summary>
        public static pbr::FileDescriptor Descriptor
        {
            get { return descriptor; }
        }
        private static pbr::FileDescriptor descriptor;

        static MensagemReflection()
        {
            byte[] descriptorData = global::System.Convert.FromBase64String(
                string.Concat(
                  "ChFNZW5zYWdlbUJEVC5wcm90bxofZ29vZ2xlL3Byb3RvYnVmL3RpbWVzdGFt",
                  "cC5wcm90byLJAQoITWVuc2FnZW0SKAoERGF0YRgBIAEoCzIaLmdvb2dsZS5w",
                  "cm90b2J1Zi5UaW1lc3RhbXASJAoIQ29udGV1ZG8YAiABKAsyEi5BZ3J1cGFt",
                  "ZW50b1RhYmVsYRIgChhJZGVudGlmaWNhZG9yQWdydXBhbWVudG8YAyABKAkS",
                  "GwoTSWRlbnRpZmljYWRvclRhYmVsYRgEIAEoCRIuCglBcGxpY2FjYW8YBSAB",
                  "KA4yGy5FbnVtSWRlbnRpZmljYWRvckFwbGljYWNhbyKNAgoRQWdydXBhbWVu",
                  "dG9UYWJlbGESDAoETm9tZRgBIAEoCRIiCglFc3RydXR1cmEYAiABKAsyDy5N",
                  "ZXRhZGFkb1RhYmVsYRJIChNEaWNpb25hcmlvTWV0YWRhZG9zGAMgAygLMisu",
                  "QWdydXBhbWVudG9UYWJlbGEuRGljaW9uYXJpb01ldGFkYWRvc0VudHJ5EhMK",
                  "C0RhdGFBcnF1aXZvGAQgASgJEhsKE1F1YW50aWRhZGVSZWdpc3Ryb3MYBSAB",
                  "KAMaSgoYRGljaW9uYXJpb01ldGFkYWRvc0VudHJ5EgsKA2tleRgBIAEoCRId",
                  "CgV2YWx1ZRgCIAEoCzIOLk1lbnNhZ2VtS2Fma2E6AjgBIoUBCg1NZW5zYWdl",
                  "bUthZmthEiEKCU1ldGFkYWRvcxgBIAMoCzIOLk1ldGFkYWRvS2Fma2ESHwoI",
                  "T3BlcmFjYW8YAiABKA4yDS5FbnVtT3BlcmFjYW8SMAoMRGF0YVJlZ2lzdHJv",
                  "GAMgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCI+Cg1NZXRhZGFk",
                  "b0thZmthEgoKAklkGAEgASgJEhIKCk5vbWVDb2x1bmEYAiABKAkSDQoFVmFs",
                  "b3IYAyABKAkiqAEKDk1ldGFkYWRvVGFiZWxhEiQKC0xpc3RhQ29sdW5hGAEg",
                  "AygLMg8uTWV0YWRhZG9Db2x1bmESDAoETm9tZRgCIAEoCRIZChFUYWJlbGFz",
                  "QXNzb2NpYWRhcxgDIAMoCRIfCghPcGVyYWNhbxgEIAEoDjINLkVudW1PcGVy",
                  "YWNhbxIMCgRGbGFnGAUgASgFEhgKEE11ZGFuY2FFc3RydXR1cmEYBiABKAgi",
                  "swEKDk1ldGFkYWRvQ29sdW5hEgoKAklkGAEgASgJEhgKEENoYXZlRXN0cmFu",
                  "Z2VpcmEYAiABKAgSFQoNQ2hhdmVQcmltYXJpYRgDIAEoCBIoCgREYXRhGAQg",
                  "ASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIMCgROb21lGAUgASgJ",
                  "Eg8KB1RhbWFuaG8YBiABKAMSDAoEVGlwbxgHIAEoCRINCgVWYWxvchgIIAEo",
                  "CSpJChpFbnVtSWRlbnRpZmljYWRvckFwbGljYWNhbxIXChNJbmZvcm1peE1v",
                  "bml0b3JTeW5jEAASEgoOSW5mb3JtaXhCRFN5bmMQASpFCgxFbnVtT3BlcmFj",
                  "YW8SCgoGTmVuaHVtEAASDAoISW5jbHVzYW8QARINCglBbHRlcmFjYW8QAhIM",
                  "CghFeGNsdXNhbxADQh2qAhpCRC5TWU5DLkluZnJhLlNoYXJlZC5Qcm90b2IG",
                  "cHJvdG8z"));
            descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
                new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
                new pbr::GeneratedClrTypeInfo(new[] { typeof(global::Infra.Shared.Proto.EnumIdentificadorAplicacao), typeof(global::Infra.Shared.Proto.EnumOperacao), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Infra.Shared.Proto.Mensagem), global::Infra.Shared.Proto.Mensagem.Parser, new[]{ "Data", "Conteudo", "IdentificadorAgrupamento", "IdentificadorTabela", "Aplicacao" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Infra.Shared.Proto.AgrupamentoTabela), global::Infra.Shared.Proto.AgrupamentoTabela.Parser, new[]{ "Nome", "Estrutura", "DicionarioMetadados", "DataArquivo", "QuantidadeRegistros" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::Infra.Shared.Proto.MensagemKafka), global::Infra.Shared.Proto.MensagemKafka.Parser, new[]{ "Metadados", "Operacao", "DataRegistro" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Infra.Shared.Proto.MetadadoKafka), global::Infra.Shared.Proto.MetadadoKafka.Parser, new[]{ "Id", "NomeColuna", "Valor" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Infra.Shared.Proto.MetadadoTabela), global::Infra.Shared.Proto.MetadadoTabela.Parser, new[]{ "ListaColuna", "Nome", "TabelasAssociadas", "Operacao", "Flag", "MudancaEstrutura" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Infra.Shared.Proto.MetadadoColuna), global::Infra.Shared.Proto.MetadadoColuna.Parser, new[]{ "Id", "ChaveEstrangeira", "ChavePrimaria", "Data", "Nome", "Tamanho", "Tipo", "Valor" }, null, null, null, null)
                }));
        }
        #endregion

    }
    #region Enums
    public enum EnumIdentificadorAplicacao
    {
        [pbr::OriginalName("Monitor")] Monitor = 0
    }

    public enum EnumOperacao
    {
        [pbr::OriginalName("Nenhum")] Nenhum = 0,
        [pbr::OriginalName("Inclusao")] Inclusao = 1,
        [pbr::OriginalName("Alteracao")] Alteracao = 2,
        [pbr::OriginalName("Exclusao")] Exclusao = 3,
    }

    #endregion

    #region Messages
    public sealed partial class Mensagem : pb::IMessage<Mensagem>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<Mensagem> _parser = new pb::MessageParser<Mensagem>(() => new Mensagem());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<Mensagem> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Infra.Shared.Proto.MensagemReflection.Descriptor.MessageTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Mensagem()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Mensagem(Mensagem other) : this()
        {
            data_ = other.data_ != null ? other.data_.Clone() : null;
            conteudo_ = other.conteudo_ != null ? other.conteudo_.Clone() : null;
            identificadorAgrupamento_ = other.identificadorAgrupamento_;
            identificadorTabela_ = other.identificadorTabela_;
            aplicacao_ = other.aplicacao_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Mensagem Clone()
        {
            return new Mensagem(this);
        }

        /// <summary>Field number for the "Data" field.</summary>
        public const int DataFieldNumber = 1;
        private global::Google.Protobuf.WellKnownTypes.Timestamp data_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::Google.Protobuf.WellKnownTypes.Timestamp Data
        {
            get { return data_; }
            set
            {
                data_ = value;
            }
        }

        /// <summary>Field number for the "Conteudo" field.</summary>
        public const int ConteudoFieldNumber = 2;
        private global::Infra.Shared.Proto.AgrupamentoTabela conteudo_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::Infra.Shared.Proto.AgrupamentoTabela Conteudo
        {
            get { return conteudo_; }
            set
            {
                conteudo_ = value;
            }
        }

        /// <summary>Field number for the "IdentificadorAgrupamento" field.</summary>
        public const int IdentificadorAgrupamentoFieldNumber = 3;
        private string identificadorAgrupamento_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string IdentificadorAgrupamento
        {
            get { return identificadorAgrupamento_; }
            set
            {
                identificadorAgrupamento_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "IdentificadorTabela" field.</summary>
        public const int IdentificadorTabelaFieldNumber = 4;
        private string identificadorTabela_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string IdentificadorTabela
        {
            get { return identificadorTabela_; }
            set
            {
                identificadorTabela_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "Aplicacao" field.</summary>
        public const int AplicacaoFieldNumber = 5;
        private global::Infra.Shared.Proto.EnumIdentificadorAplicacao aplicacao_ = global::Infra.Shared.Proto.EnumIdentificadorAplicacao.Monitor;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::Infra.Shared.Proto.EnumIdentificadorAplicacao Aplicacao
        {
            get { return aplicacao_; }
            set
            {
                aplicacao_ = value;
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other)
        {
            return Equals(other as Mensagem);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(Mensagem other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (!object.Equals(Data, other.Data)) return false;
            if (!object.Equals(Conteudo, other.Conteudo)) return false;
            if (IdentificadorAgrupamento != other.IdentificadorAgrupamento) return false;
            if (IdentificadorTabela != other.IdentificadorTabela) return false;
            if (Aplicacao != other.Aplicacao) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode()
        {
            int hash = 1;
            if (data_ != null) hash ^= Data.GetHashCode();
            if (conteudo_ != null) hash ^= Conteudo.GetHashCode();
            if (IdentificadorAgrupamento.Length != 0) hash ^= IdentificadorAgrupamento.GetHashCode();
            if (IdentificadorTabela.Length != 0) hash ^= IdentificadorTabela.GetHashCode();
            if (Aplicacao != global::Infra.Shared.Proto.EnumIdentificadorAplicacao.Monitor) hash ^= Aplicacao.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (data_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Data);
      }
      if (conteudo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Conteudo);
      }
      if (IdentificadorAgrupamento.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(IdentificadorAgrupamento);
      }
      if (IdentificadorTabela.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(IdentificadorTabela);
      }
      if (Aplicacao != global::Infra.Shared.Proto.EnumIdentificadorAplicacao.Monitor) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Aplicacao);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (data_ != null)
            {
                output.WriteRawTag(10);
                output.WriteMessage(Data);
            }
            if (conteudo_ != null)
            {
                output.WriteRawTag(18);
                output.WriteMessage(Conteudo);
            }
            if (IdentificadorAgrupamento.Length != 0)
            {
                output.WriteRawTag(26);
                output.WriteString(IdentificadorAgrupamento);
            }
            if (IdentificadorTabela.Length != 0)
            {
                output.WriteRawTag(34);
                output.WriteString(IdentificadorTabela);
            }
            if (Aplicacao != global::Infra.Shared.Proto.EnumIdentificadorAplicacao.Monitor)
            {
                output.WriteRawTag(40);
                output.WriteEnum((int)Aplicacao);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize()
        {
            int size = 0;
            if (data_ != null)
            {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
            }
            if (conteudo_ != null)
            {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(Conteudo);
            }
            if (IdentificadorAgrupamento.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(IdentificadorAgrupamento);
            }
            if (IdentificadorTabela.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(IdentificadorTabela);
            }
            if (Aplicacao != global::Infra.Shared.Proto.EnumIdentificadorAplicacao.Monitor)
            {
                size += 1 + pb::CodedOutputStream.ComputeEnumSize((int)Aplicacao);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(Mensagem other)
        {
            if (other == null)
            {
                return;
            }
            if (other.data_ != null)
            {
                if (data_ == null)
                {
                    Data = new global::Google.Protobuf.WellKnownTypes.Timestamp();
                }
                Data.MergeFrom(other.Data);
            }
            if (other.conteudo_ != null)
            {
                if (conteudo_ == null)
                {
                    Conteudo = new global::Infra.Shared.Proto.AgrupamentoTabela();
                }
                Conteudo.MergeFrom(other.Conteudo);
            }
            if (other.IdentificadorAgrupamento.Length != 0)
            {
                IdentificadorAgrupamento = other.IdentificadorAgrupamento;
            }
            if (other.IdentificadorTabela.Length != 0)
            {
                IdentificadorTabela = other.IdentificadorTabela;
            }
            if (other.Aplicacao != global::Infra.Shared.Proto.EnumIdentificadorAplicacao.Monitor)
            {
                Aplicacao = other.Aplicacao;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (data_ == null) {
              Data = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Data);
            break;
          }
          case 18: {
            if (conteudo_ == null) {
              Conteudo = new global::Infra.Shared.Proto.AgrupamentoTabela();
            }
            input.ReadMessage(Conteudo);
            break;
          }
          case 26: {
            IdentificadorAgrupamento = input.ReadString();
            break;
          }
          case 34: {
            IdentificadorTabela = input.ReadString();
            break;
          }
          case 40: {
            Aplicacao = (global::Infra.Shared.Proto.EnumIdentificadorAplicacao) input.ReadEnum();
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 10:
                        {
                            if (data_ == null)
                            {
                                Data = new global::Google.Protobuf.WellKnownTypes.Timestamp();
                            }
                            input.ReadMessage(Data);
                            break;
                        }
                    case 18:
                        {
                            if (conteudo_ == null)
                            {
                                Conteudo = new global::Infra.Shared.Proto.AgrupamentoTabela();
                            }
                            input.ReadMessage(Conteudo);
                            break;
                        }
                    case 26:
                        {
                            IdentificadorAgrupamento = input.ReadString();
                            break;
                        }
                    case 34:
                        {
                            IdentificadorTabela = input.ReadString();
                            break;
                        }
                    case 40:
                        {
                            Aplicacao = (global::Infra.Shared.Proto.EnumIdentificadorAplicacao)input.ReadEnum();
                            break;
                        }
                }
            }
        }
#endif

    }

    public sealed partial class AgrupamentoTabela : pb::IMessage<AgrupamentoTabela>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<AgrupamentoTabela> _parser = new pb::MessageParser<AgrupamentoTabela>(() => new AgrupamentoTabela());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<AgrupamentoTabela> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Infra.Shared.Proto.MensagemReflection.Descriptor.MessageTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public AgrupamentoTabela()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public AgrupamentoTabela(AgrupamentoTabela other) : this()
        {
            nome_ = other.nome_;
            estrutura_ = other.estrutura_ != null ? other.estrutura_.Clone() : null;
            dicionarioMetadados_ = other.dicionarioMetadados_.Clone();
            dataArquivo_ = other.dataArquivo_;
            quantidadeRegistros_ = other.quantidadeRegistros_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public AgrupamentoTabela Clone()
        {
            return new AgrupamentoTabela(this);
        }

        /// <summary>Field number for the "Nome" field.</summary>
        public const int NomeFieldNumber = 1;
        private string nome_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Nome
        {
            get { return nome_; }
            set
            {
                nome_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "Estrutura" field.</summary>
        public const int EstruturaFieldNumber = 2;
        private global::Infra.Shared.Proto.MetadadoTabela estrutura_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::Infra.Shared.Proto.MetadadoTabela Estrutura
        {
            get { return estrutura_; }
            set
            {
                estrutura_ = value;
            }
        }

        /// <summary>Field number for the "DicionarioMetadados" field.</summary>
        public const int DicionarioMetadadosFieldNumber = 3;
        private static readonly pbc::MapField<string, global::Infra.Shared.Proto.MensagemKafka>.Codec _map_dicionarioMetadados_codec
            = new pbc::MapField<string, global::Infra.Shared.Proto.MensagemKafka>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::Infra.Shared.Proto.MensagemKafka.Parser), 26);
        private readonly pbc::MapField<string, global::Infra.Shared.Proto.MensagemKafka> dicionarioMetadados_ = new pbc::MapField<string, global::Infra.Shared.Proto.MensagemKafka>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public pbc::MapField<string, global::Infra.Shared.Proto.MensagemKafka> DicionarioMetadados
        {
            get { return dicionarioMetadados_; }
        }

        /// <summary>Field number for the "DataArquivo" field.</summary>
        public const int DataArquivoFieldNumber = 4;
        private string dataArquivo_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string DataArquivo
        {
            get { return dataArquivo_; }
            set
            {
                dataArquivo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "QuantidadeRegistros" field.</summary>
        public const int QuantidadeRegistrosFieldNumber = 5;
        private long quantidadeRegistros_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public long QuantidadeRegistros
        {
            get { return quantidadeRegistros_; }
            set
            {
                quantidadeRegistros_ = value;
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other)
        {
            return Equals(other as AgrupamentoTabela);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(AgrupamentoTabela other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (Nome != other.Nome) return false;
            if (!object.Equals(Estrutura, other.Estrutura)) return false;
            if (!DicionarioMetadados.Equals(other.DicionarioMetadados)) return false;
            if (DataArquivo != other.DataArquivo) return false;
            if (QuantidadeRegistros != other.QuantidadeRegistros) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode()
        {
            int hash = 1;
            if (Nome.Length != 0) hash ^= Nome.GetHashCode();
            if (estrutura_ != null) hash ^= Estrutura.GetHashCode();
            hash ^= DicionarioMetadados.GetHashCode();
            if (DataArquivo.Length != 0) hash ^= DataArquivo.GetHashCode();
            if (QuantidadeRegistros != 0L) hash ^= QuantidadeRegistros.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (Nome.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Nome);
      }
      if (estrutura_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Estrutura);
      }
      dicionarioMetadados_.WriteTo(output, _map_dicionarioMetadados_codec);
      if (DataArquivo.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(DataArquivo);
      }
      if (QuantidadeRegistros != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(QuantidadeRegistros);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (Nome.Length != 0)
            {
                output.WriteRawTag(10);
                output.WriteString(Nome);
            }
            if (estrutura_ != null)
            {
                output.WriteRawTag(18);
                output.WriteMessage(Estrutura);
            }
            dicionarioMetadados_.WriteTo(ref output, _map_dicionarioMetadados_codec);
            if (DataArquivo.Length != 0)
            {
                output.WriteRawTag(34);
                output.WriteString(DataArquivo);
            }
            if (QuantidadeRegistros != 0L)
            {
                output.WriteRawTag(40);
                output.WriteInt64(QuantidadeRegistros);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize()
        {
            int size = 0;
            if (Nome.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Nome);
            }
            if (estrutura_ != null)
            {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(Estrutura);
            }
            size += dicionarioMetadados_.CalculateSize(_map_dicionarioMetadados_codec);
            if (DataArquivo.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(DataArquivo);
            }
            if (QuantidadeRegistros != 0L)
            {
                size += 1 + pb::CodedOutputStream.ComputeInt64Size(QuantidadeRegistros);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(AgrupamentoTabela other)
        {
            if (other == null)
            {
                return;
            }
            if (other.Nome.Length != 0)
            {
                Nome = other.Nome;
            }
            if (other.estrutura_ != null)
            {
                if (estrutura_ == null)
                {
                    Estrutura = new global::Infra.Shared.Proto.MetadadoTabela();
                }
                Estrutura.MergeFrom(other.Estrutura);
            }
            dicionarioMetadados_.Add(other.dicionarioMetadados_);
            if (other.DataArquivo.Length != 0)
            {
                DataArquivo = other.DataArquivo;
            }
            if (other.QuantidadeRegistros != 0L)
            {
                QuantidadeRegistros = other.QuantidadeRegistros;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Nome = input.ReadString();
            break;
          }
          case 18: {
            if (estrutura_ == null) {
              Estrutura = new global::Infra.Shared.Proto.MetadadoTabela();
            }
            input.ReadMessage(Estrutura);
            break;
          }
          case 26: {
            dicionarioMetadados_.AddEntriesFrom(input, _map_dicionarioMetadados_codec);
            break;
          }
          case 34: {
            DataArquivo = input.ReadString();
            break;
          }
          case 40: {
            QuantidadeRegistros = input.ReadInt64();
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 10:
                        {
                            Nome = input.ReadString();
                            break;
                        }
                    case 18:
                        {
                            if (estrutura_ == null)
                            {
                                Estrutura = new global::Infra.Shared.Proto.MetadadoTabela();
                            }
                            input.ReadMessage(Estrutura);
                            break;
                        }
                    case 26:
                        {
                            dicionarioMetadados_.AddEntriesFrom(ref input, _map_dicionarioMetadados_codec);
                            break;
                        }
                    case 34:
                        {
                            DataArquivo = input.ReadString();
                            break;
                        }
                    case 40:
                        {
                            QuantidadeRegistros = input.ReadInt64();
                            break;
                        }
                }
            }
        }
#endif

    }

    public sealed partial class MensagemKafka : pb::IMessage<MensagemKafka>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<MensagemKafka> _parser = new pb::MessageParser<MensagemKafka>(() => new MensagemKafka());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<MensagemKafka> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Infra.Shared.Proto.MensagemReflection.Descriptor.MessageTypes[2]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public MensagemKafka()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public MensagemKafka(MensagemKafka other) : this()
        {
            metadados_ = other.metadados_.Clone();
            operacao_ = other.operacao_;
            dataRegistro_ = other.dataRegistro_ != null ? other.dataRegistro_.Clone() : null;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public MensagemKafka Clone()
        {
            return new MensagemKafka(this);
        }

        /// <summary>Field number for the "Metadados" field.</summary>
        public const int MetadadosFieldNumber = 1;
        private static readonly pb::FieldCodec<global::Infra.Shared.Proto.MetadadoKafka> _repeated_metadados_codec
            = pb::FieldCodec.ForMessage(10, global::Infra.Shared.Proto.MetadadoKafka.Parser);
        private readonly pbc::RepeatedField<global::Infra.Shared.Proto.MetadadoKafka> metadados_ = new pbc::RepeatedField<global::Infra.Shared.Proto.MetadadoKafka>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public pbc::RepeatedField<global::Infra.Shared.Proto.MetadadoKafka> Metadados
        {
            get { return metadados_; }
        }

        /// <summary>Field number for the "Operacao" field.</summary>
        public const int OperacaoFieldNumber = 2;
        private global::Infra.Shared.Proto.EnumOperacao operacao_ = global::Infra.Shared.Proto.EnumOperacao.Nenhum;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::Infra.Shared.Proto.EnumOperacao Operacao
        {
            get { return operacao_; }
            set
            {
                operacao_ = value;
            }
        }

        /// <summary>Field number for the "DataRegistro" field.</summary>
        public const int DataRegistroFieldNumber = 3;
        private global::Google.Protobuf.WellKnownTypes.Timestamp dataRegistro_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::Google.Protobuf.WellKnownTypes.Timestamp DataRegistro
        {
            get { return dataRegistro_; }
            set
            {
                dataRegistro_ = value;
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other)
        {
            return Equals(other as MensagemKafka);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(MensagemKafka other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (!metadados_.Equals(other.metadados_)) return false;
            if (Operacao != other.Operacao) return false;
            if (!object.Equals(DataRegistro, other.DataRegistro)) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode()
        {
            int hash = 1;
            hash ^= metadados_.GetHashCode();
            if (Operacao != global::Infra.Shared.Proto.EnumOperacao.Nenhum) hash ^= Operacao.GetHashCode();
            if (dataRegistro_ != null) hash ^= DataRegistro.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      metadados_.WriteTo(output, _repeated_metadados_codec);
      if (Operacao != global::Infra.Shared.Proto.EnumOperacao.Nenhum) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Operacao);
      }
      if (dataRegistro_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(DataRegistro);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            metadados_.WriteTo(ref output, _repeated_metadados_codec);
            if (Operacao != global::Infra.Shared.Proto.EnumOperacao.Nenhum)
            {
                output.WriteRawTag(16);
                output.WriteEnum((int)Operacao);
            }
            if (dataRegistro_ != null)
            {
                output.WriteRawTag(26);
                output.WriteMessage(DataRegistro);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize()
        {
            int size = 0;
            size += metadados_.CalculateSize(_repeated_metadados_codec);
            if (Operacao != global::Infra.Shared.Proto.EnumOperacao.Nenhum)
            {
                size += 1 + pb::CodedOutputStream.ComputeEnumSize((int)Operacao);
            }
            if (dataRegistro_ != null)
            {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(DataRegistro);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(MensagemKafka other)
        {
            if (other == null)
            {
                return;
            }
            metadados_.Add(other.metadados_);
            if (other.Operacao != global::Infra.Shared.Proto.EnumOperacao.Nenhum)
            {
                Operacao = other.Operacao;
            }
            if (other.dataRegistro_ != null)
            {
                if (dataRegistro_ == null)
                {
                    DataRegistro = new global::Google.Protobuf.WellKnownTypes.Timestamp();
                }
                DataRegistro.MergeFrom(other.DataRegistro);
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            metadados_.AddEntriesFrom(input, _repeated_metadados_codec);
            break;
          }
          case 16: {
            Operacao = (global::Infra.Shared.Proto.EnumOperacao) input.ReadEnum();
            break;
          }
          case 26: {
            if (dataRegistro_ == null) {
              DataRegistro = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(DataRegistro);
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 10:
                        {
                            metadados_.AddEntriesFrom(ref input, _repeated_metadados_codec);
                            break;
                        }
                    case 16:
                        {
                            Operacao = (global::Infra.Shared.Proto.EnumOperacao)input.ReadEnum();
                            break;
                        }
                    case 26:
                        {
                            if (dataRegistro_ == null)
                            {
                                DataRegistro = new global::Google.Protobuf.WellKnownTypes.Timestamp();
                            }
                            input.ReadMessage(DataRegistro);
                            break;
                        }
                }
            }
        }
#endif

    }

    public sealed partial class MetadadoKafka : pb::IMessage<MetadadoKafka>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<MetadadoKafka> _parser = new pb::MessageParser<MetadadoKafka>(() => new MetadadoKafka());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<MetadadoKafka> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Infra.Shared.Proto.MensagemReflection.Descriptor.MessageTypes[3]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public MetadadoKafka()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public MetadadoKafka(MetadadoKafka other) : this()
        {
            id_ = other.id_;
            nomeColuna_ = other.nomeColuna_;
            valor_ = other.valor_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public MetadadoKafka Clone()
        {
            return new MetadadoKafka(this);
        }

        /// <summary>Field number for the "Id" field.</summary>
        public const int IdFieldNumber = 1;
        private string id_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Id
        {
            get { return id_; }
            set
            {
                id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "NomeColuna" field.</summary>
        public const int NomeColunaFieldNumber = 2;
        private string nomeColuna_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string NomeColuna
        {
            get { return nomeColuna_; }
            set
            {
                nomeColuna_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "Valor" field.</summary>
        public const int ValorFieldNumber = 3;
        private string valor_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Valor
        {
            get { return valor_; }
            set
            {
                valor_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other)
        {
            return Equals(other as MetadadoKafka);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(MetadadoKafka other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (Id != other.Id) return false;
            if (NomeColuna != other.NomeColuna) return false;
            if (Valor != other.Valor) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode()
        {
            int hash = 1;
            if (Id.Length != 0) hash ^= Id.GetHashCode();
            if (NomeColuna.Length != 0) hash ^= NomeColuna.GetHashCode();
            if (Valor.Length != 0) hash ^= Valor.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (NomeColuna.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(NomeColuna);
      }
      if (Valor.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Valor);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (Id.Length != 0)
            {
                output.WriteRawTag(10);
                output.WriteString(Id);
            }
            if (NomeColuna.Length != 0)
            {
                output.WriteRawTag(18);
                output.WriteString(NomeColuna);
            }
            if (Valor.Length != 0)
            {
                output.WriteRawTag(26);
                output.WriteString(Valor);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize()
        {
            int size = 0;
            if (Id.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
            }
            if (NomeColuna.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(NomeColuna);
            }
            if (Valor.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Valor);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(MetadadoKafka other)
        {
            if (other == null)
            {
                return;
            }
            if (other.Id.Length != 0)
            {
                Id = other.Id;
            }
            if (other.NomeColuna.Length != 0)
            {
                NomeColuna = other.NomeColuna;
            }
            if (other.Valor.Length != 0)
            {
                Valor = other.Valor;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            NomeColuna = input.ReadString();
            break;
          }
          case 26: {
            Valor = input.ReadString();
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 10:
                        {
                            Id = input.ReadString();
                            break;
                        }
                    case 18:
                        {
                            NomeColuna = input.ReadString();
                            break;
                        }
                    case 26:
                        {
                            Valor = input.ReadString();
                            break;
                        }
                }
            }
        }
#endif

    }

    public sealed partial class MetadadoTabela : pb::IMessage<MetadadoTabela>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<MetadadoTabela> _parser = new pb::MessageParser<MetadadoTabela>(() => new MetadadoTabela());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<MetadadoTabela> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Infra.Shared.Proto.MensagemReflection.Descriptor.MessageTypes[4]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public MetadadoTabela()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public MetadadoTabela(MetadadoTabela other) : this()
        {
            listaColuna_ = other.listaColuna_.Clone();
            nome_ = other.nome_;
            tabelasAssociadas_ = other.tabelasAssociadas_.Clone();
            operacao_ = other.operacao_;
            flag_ = other.flag_;
            mudancaEstrutura_ = other.mudancaEstrutura_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public MetadadoTabela Clone()
        {
            return new MetadadoTabela(this);
        }

        /// <summary>Field number for the "ListaColuna" field.</summary>
        public const int ListaColunaFieldNumber = 1;
        private static readonly pb::FieldCodec<global::Infra.Shared.Proto.MetadadoColuna> _repeated_listaColuna_codec
            = pb::FieldCodec.ForMessage(10, global::Infra.Shared.Proto.MetadadoColuna.Parser);
        private readonly pbc::RepeatedField<global::Infra.Shared.Proto.MetadadoColuna> listaColuna_ = new pbc::RepeatedField<global::Infra.Shared.Proto.MetadadoColuna>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public pbc::RepeatedField<global::Infra.Shared.Proto.MetadadoColuna> ListaColuna
        {
            get { return listaColuna_; }
        }

        /// <summary>Field number for the "Nome" field.</summary>
        public const int NomeFieldNumber = 2;
        private string nome_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Nome
        {
            get { return nome_; }
            set
            {
                nome_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "TabelasAssociadas" field.</summary>
        public const int TabelasAssociadasFieldNumber = 3;
        private static readonly pb::FieldCodec<string> _repeated_tabelasAssociadas_codec
            = pb::FieldCodec.ForString(26);
        private readonly pbc::RepeatedField<string> tabelasAssociadas_ = new pbc::RepeatedField<string>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public pbc::RepeatedField<string> TabelasAssociadas
        {
            get { return tabelasAssociadas_; }
        }

        /// <summary>Field number for the "Operacao" field.</summary>
        public const int OperacaoFieldNumber = 4;
        private global::Infra.Shared.Proto.EnumOperacao operacao_ = global::Infra.Shared.Proto.EnumOperacao.Nenhum;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::Infra.Shared.Proto.EnumOperacao Operacao
        {
            get { return operacao_; }
            set
            {
                operacao_ = value;
            }
        }

        /// <summary>Field number for the "Flag" field.</summary>
        public const int FlagFieldNumber = 5;
        private int flag_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int Flag
        {
            get { return flag_; }
            set
            {
                flag_ = value;
            }
        }

        /// <summary>Field number for the "MudancaEstrutura" field.</summary>
        public const int MudancaEstruturaFieldNumber = 6;
        private bool mudancaEstrutura_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool MudancaEstrutura
        {
            get { return mudancaEstrutura_; }
            set
            {
                mudancaEstrutura_ = value;
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other)
        {
            return Equals(other as MetadadoTabela);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(MetadadoTabela other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (!listaColuna_.Equals(other.listaColuna_)) return false;
            if (Nome != other.Nome) return false;
            if (!tabelasAssociadas_.Equals(other.tabelasAssociadas_)) return false;
            if (Operacao != other.Operacao) return false;
            if (Flag != other.Flag) return false;
            if (MudancaEstrutura != other.MudancaEstrutura) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode()
        {
            int hash = 1;
            hash ^= listaColuna_.GetHashCode();
            if (Nome.Length != 0) hash ^= Nome.GetHashCode();
            hash ^= tabelasAssociadas_.GetHashCode();
            if (Operacao != global::Infra.Shared.Proto.EnumOperacao.Nenhum) hash ^= Operacao.GetHashCode();
            if (Flag != 0) hash ^= Flag.GetHashCode();
            if (MudancaEstrutura != false) hash ^= MudancaEstrutura.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      listaColuna_.WriteTo(output, _repeated_listaColuna_codec);
      if (Nome.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Nome);
      }
      tabelasAssociadas_.WriteTo(output, _repeated_tabelasAssociadas_codec);
      if (Operacao != global::Infra.Shared.Proto.EnumOperacao.Nenhum) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Operacao);
      }
      if (Flag != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Flag);
      }
      if (MudancaEstrutura != false) {
        output.WriteRawTag(48);
        output.WriteBool(MudancaEstrutura);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            listaColuna_.WriteTo(ref output, _repeated_listaColuna_codec);
            if (Nome.Length != 0)
            {
                output.WriteRawTag(18);
                output.WriteString(Nome);
            }
            tabelasAssociadas_.WriteTo(ref output, _repeated_tabelasAssociadas_codec);
            if (Operacao != global::Infra.Shared.Proto.EnumOperacao.Nenhum)
            {
                output.WriteRawTag(32);
                output.WriteEnum((int)Operacao);
            }
            if (Flag != 0)
            {
                output.WriteRawTag(40);
                output.WriteInt32(Flag);
            }
            if (MudancaEstrutura != false)
            {
                output.WriteRawTag(48);
                output.WriteBool(MudancaEstrutura);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize()
        {
            int size = 0;
            size += listaColuna_.CalculateSize(_repeated_listaColuna_codec);
            if (Nome.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Nome);
            }
            size += tabelasAssociadas_.CalculateSize(_repeated_tabelasAssociadas_codec);
            if (Operacao != global::Infra.Shared.Proto.EnumOperacao.Nenhum)
            {
                size += 1 + pb::CodedOutputStream.ComputeEnumSize((int)Operacao);
            }
            if (Flag != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeInt32Size(Flag);
            }
            if (MudancaEstrutura != false)
            {
                size += 1 + 1;
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(MetadadoTabela other)
        {
            if (other == null)
            {
                return;
            }
            listaColuna_.Add(other.listaColuna_);
            if (other.Nome.Length != 0)
            {
                Nome = other.Nome;
            }
            tabelasAssociadas_.Add(other.tabelasAssociadas_);
            if (other.Operacao != global::Infra.Shared.Proto.EnumOperacao.Nenhum)
            {
                Operacao = other.Operacao;
            }
            if (other.Flag != 0)
            {
                Flag = other.Flag;
            }
            if (other.MudancaEstrutura != false)
            {
                MudancaEstrutura = other.MudancaEstrutura;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            listaColuna_.AddEntriesFrom(input, _repeated_listaColuna_codec);
            break;
          }
          case 18: {
            Nome = input.ReadString();
            break;
          }
          case 26: {
            tabelasAssociadas_.AddEntriesFrom(input, _repeated_tabelasAssociadas_codec);
            break;
          }
          case 32: {
            Operacao = (global::Infra.Shared.Proto.EnumOperacao) input.ReadEnum();
            break;
          }
          case 40: {
            Flag = input.ReadInt32();
            break;
          }
          case 48: {
            MudancaEstrutura = input.ReadBool();
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 10:
                        {
                            listaColuna_.AddEntriesFrom(ref input, _repeated_listaColuna_codec);
                            break;
                        }
                    case 18:
                        {
                            Nome = input.ReadString();
                            break;
                        }
                    case 26:
                        {
                            tabelasAssociadas_.AddEntriesFrom(ref input, _repeated_tabelasAssociadas_codec);
                            break;
                        }
                    case 32:
                        {
                            Operacao = (global::Infra.Shared.Proto.EnumOperacao)input.ReadEnum();
                            break;
                        }
                    case 40:
                        {
                            Flag = input.ReadInt32();
                            break;
                        }
                    case 48:
                        {
                            MudancaEstrutura = input.ReadBool();
                            break;
                        }
                }
            }
        }
#endif

    }

    public sealed partial class MetadadoColuna : pb::IMessage<MetadadoColuna>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<MetadadoColuna> _parser = new pb::MessageParser<MetadadoColuna>(() => new MetadadoColuna());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<MetadadoColuna> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Infra.Shared.Proto.MensagemReflection.Descriptor.MessageTypes[5]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public MetadadoColuna()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public MetadadoColuna(MetadadoColuna other) : this()
        {
            id_ = other.id_;
            chaveEstrangeira_ = other.chaveEstrangeira_;
            chavePrimaria_ = other.chavePrimaria_;
            data_ = other.data_ != null ? other.data_.Clone() : null;
            nome_ = other.nome_;
            tamanho_ = other.tamanho_;
            tipo_ = other.tipo_;
            valor_ = other.valor_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public MetadadoColuna Clone()
        {
            return new MetadadoColuna(this);
        }

        /// <summary>Field number for the "Id" field.</summary>
        public const int IdFieldNumber = 1;
        private string id_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Id
        {
            get { return id_; }
            set
            {
                id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "ChaveEstrangeira" field.</summary>
        public const int ChaveEstrangeiraFieldNumber = 2;
        private bool chaveEstrangeira_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool ChaveEstrangeira
        {
            get { return chaveEstrangeira_; }
            set
            {
                chaveEstrangeira_ = value;
            }
        }

        /// <summary>Field number for the "ChavePrimaria" field.</summary>
        public const int ChavePrimariaFieldNumber = 3;
        private bool chavePrimaria_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool ChavePrimaria
        {
            get { return chavePrimaria_; }
            set
            {
                chavePrimaria_ = value;
            }
        }

        /// <summary>Field number for the "Data" field.</summary>
        public const int DataFieldNumber = 4;
        private global::Google.Protobuf.WellKnownTypes.Timestamp data_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::Google.Protobuf.WellKnownTypes.Timestamp Data
        {
            get { return data_; }
            set
            {
                data_ = value;
            }
        }

        /// <summary>Field number for the "Nome" field.</summary>
        public const int NomeFieldNumber = 5;
        private string nome_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Nome
        {
            get { return nome_; }
            set
            {
                nome_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "Tamanho" field.</summary>
        public const int TamanhoFieldNumber = 6;
        private long tamanho_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public long Tamanho
        {
            get { return tamanho_; }
            set
            {
                tamanho_ = value;
            }
        }

        /// <summary>Field number for the "Tipo" field.</summary>
        public const int TipoFieldNumber = 7;
        private string tipo_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Tipo
        {
            get { return tipo_; }
            set
            {
                tipo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "Valor" field.</summary>
        public const int ValorFieldNumber = 8;
        private string valor_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Valor
        {
            get { return valor_; }
            set
            {
                valor_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other)
        {
            return Equals(other as MetadadoColuna);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(MetadadoColuna other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (Id != other.Id) return false;
            if (ChaveEstrangeira != other.ChaveEstrangeira) return false;
            if (ChavePrimaria != other.ChavePrimaria) return false;
            if (!object.Equals(Data, other.Data)) return false;
            if (Nome != other.Nome) return false;
            if (Tamanho != other.Tamanho) return false;
            if (Tipo != other.Tipo) return false;
            if (Valor != other.Valor) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode()
        {
            int hash = 1;
            if (Id.Length != 0) hash ^= Id.GetHashCode();
            if (ChaveEstrangeira != false) hash ^= ChaveEstrangeira.GetHashCode();
            if (ChavePrimaria != false) hash ^= ChavePrimaria.GetHashCode();
            if (data_ != null) hash ^= Data.GetHashCode();
            if (Nome.Length != 0) hash ^= Nome.GetHashCode();
            if (Tamanho != 0L) hash ^= Tamanho.GetHashCode();
            if (Tipo.Length != 0) hash ^= Tipo.GetHashCode();
            if (Valor.Length != 0) hash ^= Valor.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (ChaveEstrangeira != false) {
        output.WriteRawTag(16);
        output.WriteBool(ChaveEstrangeira);
      }
      if (ChavePrimaria != false) {
        output.WriteRawTag(24);
        output.WriteBool(ChavePrimaria);
      }
      if (data_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Data);
      }
      if (Nome.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Nome);
      }
      if (Tamanho != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(Tamanho);
      }
      if (Tipo.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Tipo);
      }
      if (Valor.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Valor);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (Id.Length != 0)
            {
                output.WriteRawTag(10);
                output.WriteString(Id);
            }
            if (ChaveEstrangeira != false)
            {
                output.WriteRawTag(16);
                output.WriteBool(ChaveEstrangeira);
            }
            if (ChavePrimaria != false)
            {
                output.WriteRawTag(24);
                output.WriteBool(ChavePrimaria);
            }
            if (data_ != null)
            {
                output.WriteRawTag(34);
                output.WriteMessage(Data);
            }
            if (Nome.Length != 0)
            {
                output.WriteRawTag(42);
                output.WriteString(Nome);
            }
            if (Tamanho != 0L)
            {
                output.WriteRawTag(48);
                output.WriteInt64(Tamanho);
            }
            if (Tipo.Length != 0)
            {
                output.WriteRawTag(58);
                output.WriteString(Tipo);
            }
            if (Valor.Length != 0)
            {
                output.WriteRawTag(66);
                output.WriteString(Valor);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize()
        {
            int size = 0;
            if (Id.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
            }
            if (ChaveEstrangeira != false)
            {
                size += 1 + 1;
            }
            if (ChavePrimaria != false)
            {
                size += 1 + 1;
            }
            if (data_ != null)
            {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
            }
            if (Nome.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Nome);
            }
            if (Tamanho != 0L)
            {
                size += 1 + pb::CodedOutputStream.ComputeInt64Size(Tamanho);
            }
            if (Tipo.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Tipo);
            }
            if (Valor.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Valor);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(MetadadoColuna other)
        {
            if (other == null)
            {
                return;
            }
            if (other.Id.Length != 0)
            {
                Id = other.Id;
            }
            if (other.ChaveEstrangeira != false)
            {
                ChaveEstrangeira = other.ChaveEstrangeira;
            }
            if (other.ChavePrimaria != false)
            {
                ChavePrimaria = other.ChavePrimaria;
            }
            if (other.data_ != null)
            {
                if (data_ == null)
                {
                    Data = new global::Google.Protobuf.WellKnownTypes.Timestamp();
                }
                Data.MergeFrom(other.Data);
            }
            if (other.Nome.Length != 0)
            {
                Nome = other.Nome;
            }
            if (other.Tamanho != 0L)
            {
                Tamanho = other.Tamanho;
            }
            if (other.Tipo.Length != 0)
            {
                Tipo = other.Tipo;
            }
            if (other.Valor.Length != 0)
            {
                Valor = other.Valor;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 16: {
            ChaveEstrangeira = input.ReadBool();
            break;
          }
          case 24: {
            ChavePrimaria = input.ReadBool();
            break;
          }
          case 34: {
            if (data_ == null) {
              Data = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Data);
            break;
          }
          case 42: {
            Nome = input.ReadString();
            break;
          }
          case 48: {
            Tamanho = input.ReadInt64();
            break;
          }
          case 58: {
            Tipo = input.ReadString();
            break;
          }
          case 66: {
            Valor = input.ReadString();
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 10:
                        {
                            Id = input.ReadString();
                            break;
                        }
                    case 16:
                        {
                            ChaveEstrangeira = input.ReadBool();
                            break;
                        }
                    case 24:
                        {
                            ChavePrimaria = input.ReadBool();
                            break;
                        }
                    case 34:
                        {
                            if (data_ == null)
                            {
                                Data = new global::Google.Protobuf.WellKnownTypes.Timestamp();
                            }
                            input.ReadMessage(Data);
                            break;
                        }
                    case 42:
                        {
                            Nome = input.ReadString();
                            break;
                        }
                    case 48:
                        {
                            Tamanho = input.ReadInt64();
                            break;
                        }
                    case 58:
                        {
                            Tipo = input.ReadString();
                            break;
                        }
                    case 66:
                        {
                            Valor = input.ReadString();
                            break;
                        }
                }
            }
        }
#endif

    }

    #endregion

}

#endregion Designer generated code
